title:       "Satiri Sahabatku Pahlawan Betawi"
version:     "003---15-Jul-2021"
copyright:   "2021-2021"
description: >- 
     Satiri, Sahabatku Pahlawan Betawi
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-14"
author:           "R. Alamsyah"
address:          "Jakarta"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://satiri.vlsm.org/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/Belajar-Latex/satiri/"
urlghpage:        "https://sitiri.vlsm.org/"
keywords:         "Dr. Ir. Satiri M. Zen, MBA"
github:           [metadata]

